# 部署在服务器上的mysql信息
spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/blog_sys_spring?characterEncoding=utf8&useSSL=false
    username: root
    password: '@hlbHLB010024@'
    driver-class-name: com.mysql.cj.jdbc.Driver
mybatis:
  configuration:
    map-underscore-to-camel-case: true #配置驼峰自动转换
#    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl #打印Sql语句
  mapper-locations: classpath:mapper/**Mapper.xml
# 设置日志路径
logging:
  file:
    name: spring-blog.log

# 通过配置文件生成验证码
kaptcha:
  border:
    enbaled: true
  text-producer:
    character:
      length: 5
    font:
      color: black
  image:
    height: 50
    width: 150
  items:
    admin:
      # 生成器访问的路径
      path: /admin/captcha
      # 生成的验证码存储在session中
      session:
        key: CAPTCHA_SESSION_KEY
        date: CAPTCHA_SESSION_DATE