# 配置数据库信息
spring:
  datasource:
     url: jdbc:mysql://127.0.0.1:3306/book_sys?characterEncoding=utf8&useSSL=false
     username: 'root'
     password: '000000'
     driver-class-name: com.mysql.cj.jdbc.Driver
# 配置 小驼峰 自动转换
mybatis:
  configuration:
    map-underscore-to-camel-case: true
    # 配置打印 MyBatis日志(SQL语句)
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  # 配置 Xml 路径
  mapper-locations: classpath:mapper/**Mapper.xml
# 设置日志⽂件的文件名
logging:
  file:
    name: spring-book.log

# 通过配置文件生成验证码
kaptcha:
  border:
    enbaled: true
  text-producer:
    character:
      length: 5
    font:
      color: black
  image:
    height: 50
    width: 150
  items:
    admin:
      # 生成器访问的路径
      path: /admin/captcha
      # 生成的验证码存储在session中
      session:
        key: CAPTCHA_SESSION_KEY
        date: CAPTCHA_SESSION_DATE